### ISSUE TITLE
Reset or Clear a Limit

### ISSUE THREAD

**Issue by patramsey** [mennanov/limiters#19]
Hello,

It does not appear that this package allows for the reset of a limit, is that correct? I have come across a use case where rate limits need to be reset. A user forgets their password, gets rate limited logging into their account. They successfully reset their password, the previous limit should be cleared so they are allowed to attempt to login again. 

Would you consider a PR for this feature?

**Comment by mennanov** [comment]
I think this is a useful feature, PR would be more than welcomed!

**Comment by mennanov** [comment]
@patramsey would you be interested in creating a pull request with the feature you described? I'd be happy to review and merge it.
Thanks!

**Comment by Madraceee** [comment]
Hey, This looks interesting and I also want to learn this repository. Can I solve this issue or is it already solved?

**Comment by mennanov** [comment]
This is not solved. If you're interested in implementing it please consider making a pull request 

Thanks!

**Comment by Madraceee** [comment]
I will look into this issue.
If I have any doubts , can I ask them here?

**Comment by Madraceee** [comment]
If my understanding is right, For each algo(token Bucket, leaky bucket etc), I need to write another function similar to Limit which resets the state of the backend?

**Comment by mennanov** [comment]
Right. You will also need to add tests for each of them in a similar way it's done for the Limit() method

**Comment by mennanov** [comment]
Resolved in https://github.com/mennanov/limiters/pull/91
