### ISSUE TITLE
question/clarification about fixed window counter lock

### ISSUE THREAD

**Issue by andresvia** [mennanov/limiters#24]
`README.md` states that:

```
Fixed window counter
Simple and resources efficient algorithm that does not need a lock.
```

But the implementation uses a lock [link](https://github.com/mennanov/limiters/blob/0b557ff90fb030cd730d372ee1ba148900f14a59/fixedwindow.go#L46-L50)

https://github.com/mennanov/limiters/blob/0b557ff90fb030cd730d372ee1ba148900f14a59/fixedwindow.go#L46-L50

I'm confused.

**Comment by mennanov** [comment]
`f.mu` is `sync.Mutex` which is a local Mutex not a distributed one (which requires additional services like etcd, redis, etc).

**Comment by mennanov** [comment]
Hm... good point. I think you're right and the Mutex in the `FixedWindowInMemory` does not seem necessary.
Could you check if it can be safely removed?

**Comment by mennanov** [comment]
@andresvia would you be interested in creating a pull request with this change?
