### ISSUE TITLE
epsilon in slidingWindow

### ISSUE THREAD

**Issue by dilshans2k** [mennanov/limiters#5]
Hi,
Could you please explain what should be ideal value of epsilon in `slidingWindow`.
Here is my current configuration
```
slidingLimiter := registry.GetOrCreate(ip, func() interface{} {
		return limiters.NewSlidingWindow(100, window, limiters.NewSlidingWindowRedis(redisClient, ip), clock, 60)
	}, 0*time.Second, clock.Now())

	t, err := slidingLimiter.(*limiters.SlidingWindow).Limit(req.Context())
	fmt.Println("timeDuration: ", t)
	if err == limiters.ErrLimitExhausted {
		wrt.WriteHeader(http.StatusTooManyRequests)
		return
	} else if err != nil {
		// The limiter failed. This error should be logged and examined.
		wrt.WriteHeader(http.StatusInternalServerError)
		return
	}

	serveWebSocket(wrt, req)
```

When i run a load test, 
Sometimes i get this panic
![image](https://user-images.githubusercontent.com/67574348/220016367-7f8a0405-1b02-46e8-b7c0-81582e8055c8.png)

And other times, server breaks, but gives no error, only go routine ids

Please help

**Comment by mennanov** [comment]
Take a look at the tests which set the epsilon value: https://github.com/mennanov/limiters/blob/master/slidingwindow_test.go#L42

Examples on how to use the registry: https://github.com/mennanov/limiters/blob/master/examples/example_grpc_ip_limiter_test.go#L24

Let me know if you still have any errors
