### ISSUE TITLE
Lock vs Unlock context aware

### ISSUE THREAD

**Issue by slunak** [mennanov/limiters#6]
Hello. Is there any particular reason why locker's `Lock` is context aware but `Unlock` is not?

https://github.com/mennanov/limiters/blob/db05502529f59994f75be429d2e5bb751272af7d/locks.go#L14

I am implementing redis locker which needs to be context aware during `Lock` and `Unlock`.

**Comment by mennanov** [comment]
Hm.. I can't remember why I decided to make `Unlock` without a context. Would you like to create a PR?
